// Generated by gencpp from file motor_control/PwmArray.msg
// DO NOT EDIT!


#ifndef MOTOR_CONTROL_MESSAGE_PWMARRAY_H
#define MOTOR_CONTROL_MESSAGE_PWMARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace motor_control
{
template <class ContainerAllocator>
struct PwmArray_
{
  typedef PwmArray_<ContainerAllocator> Type;

  PwmArray_()
    : pwm_values()  {
      pwm_values.assign(0);
  }
  PwmArray_(const ContainerAllocator& _alloc)
    : pwm_values()  {
  (void)_alloc;
      pwm_values.assign(0);
  }



   typedef boost::array<int32_t, 6>  _pwm_values_type;
  _pwm_values_type pwm_values;





  typedef boost::shared_ptr< ::motor_control::PwmArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::motor_control::PwmArray_<ContainerAllocator> const> ConstPtr;

}; // struct PwmArray_

typedef ::motor_control::PwmArray_<std::allocator<void> > PwmArray;

typedef boost::shared_ptr< ::motor_control::PwmArray > PwmArrayPtr;
typedef boost::shared_ptr< ::motor_control::PwmArray const> PwmArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::motor_control::PwmArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::motor_control::PwmArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::motor_control::PwmArray_<ContainerAllocator1> & lhs, const ::motor_control::PwmArray_<ContainerAllocator2> & rhs)
{
  return lhs.pwm_values == rhs.pwm_values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::motor_control::PwmArray_<ContainerAllocator1> & lhs, const ::motor_control::PwmArray_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace motor_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::motor_control::PwmArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::motor_control::PwmArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::PwmArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::motor_control::PwmArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::PwmArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::motor_control::PwmArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::motor_control::PwmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd3f5c6582467ef6ecc8c0b440e1fb77";
  }

  static const char* value(const ::motor_control::PwmArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd3f5c6582467ef6ULL;
  static const uint64_t static_value2 = 0xecc8c0b440e1fb77ULL;
};

template<class ContainerAllocator>
struct DataType< ::motor_control::PwmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "motor_control/PwmArray";
  }

  static const char* value(const ::motor_control::PwmArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::motor_control::PwmArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[6] pwm_values\n"
;
  }

  static const char* value(const ::motor_control::PwmArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::motor_control::PwmArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pwm_values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PwmArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::motor_control::PwmArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::motor_control::PwmArray_<ContainerAllocator>& v)
  {
    s << indent << "pwm_values[]" << std::endl;
    for (size_t i = 0; i < v.pwm_values.size(); ++i)
    {
      s << indent << "  pwm_values[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pwm_values[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOTOR_CONTROL_MESSAGE_PWMARRAY_H
