<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minesweeper">
  <link name = "link"/>

  <xacro:property name="c_middle_x" value="0.15"/>
  <xacro:property name="c_middle_y" value="0.01"/>
  <xacro:property name="c_middle_z" value="0.05"/>

  <xacro:property name="c_top_x" value="0.15"/>
  <xacro:property name="c_top_y" value="0.04"/>
  <xacro:property name="c_top_z" value="0.01"/>

   <link name="base_link">
    <visual>
      <geometry>
        <box size="${c_middle_x} ${c_middle_y} ${c_middle_z}"/>
      </geometry>
      <origin xyz = "0 0 ${c_middle_z/2}"/> 
    </visual>
    <visual>
      <geometry>
        <box size="${c_top_x} ${c_top_y} ${c_top_z}"/>
      </geometry>
      <origin xyz = "0 ${c_top_y/2 - c_middle_y/2} ${c_middle_z + c_top_z/2}"/>
    </visual>
        <visual>
      <geometry>
        <box size="${c_top_x} ${c_top_y} ${c_top_z}"/>
      </geometry>
      <origin xyz = "0 ${c_top_y/2 - c_middle_y/2} ${- c_top_z/2}"/>
    </visual>
  </link>

  <joint name = "base_joint" type="fixed">
    <parent link = "link"/>
    <child link="base_link"/>
    <origin xyz = "0 0 0.1"/> <!-- 0.1 just for visualization-->
  </joint>

  <xacro:property name="component_plate_x" value="0.15"/>
  <xacro:property name="component_plate_y" value="0.15"/>
  <xacro:property name="component_plate_z" value="0.005"/>
  
  <xacro:property name="component_rod_length" value="0.15"/>
  <xacro:property name="component_rod_radius" value="0.01"/>

  <link name = "component_plate_link">
    <visual>
      <geometry>
        <box size = "${component_plate_x} ${component_plate_y} ${component_plate_z}"/>
      </geometry>
      <origin xyz = "0 0 0"/>
      <material name="translucent_glass">
        <color rgba="0.8 0.8 0.8 0.5"/> <!-- Adjust the RGBA values for your desired color and opacity -->
      </material>
    </visual>
    <visual>
      <geometry>
        <cylinder length="${component_rod_length}" radius="${component_rod_radius}"/>
      </geometry>
      <origin xyz = "0 0 ${c_middle_z/2}" rpy = "${pi/2} 0 0"/>
      <material name="steel">
        <color rgba="0.5 0.5 0.5 1"/> <!-- Adjust the RGBA values for your desired color and opacity -->
      </material>
    </visual>
  </link>

 <joint name = "component_plate_joint" type="fixed">
    <parent link = "base_link"/>
    <child link = "component_plate_link"/>
    <origin xyz = "0 ${component_plate_y/2 + c_middle_y/2} ${component_plate_z/2}"/>
  </joint>

   <link name="mirror_base_link">
    <visual>
      <geometry>
        <box size="${c_middle_x} ${c_middle_y} ${c_middle_z}"/>
      </geometry>
      <origin xyz = "0 0 ${c_middle_z/2}"/> 
    </visual>
    <visual>
      <geometry>
        <box size="${c_top_x} ${c_top_y} ${c_top_z}"/>
      </geometry>
      <origin xyz = "0 ${-c_top_y/2 + c_middle_y/2} ${c_middle_z + c_top_z/2}"/>
    </visual>
        <visual>
      <geometry>
        <box size="${c_top_x} ${c_top_y} ${c_top_z}"/>
      </geometry>
      <origin xyz = "0 ${-c_top_y/2 + c_middle_y/2} ${- c_top_z/2}"/>
    </visual>
  </link>

  <joint name = "mirror_base_joint" type="fixed">
    <parent link = "base_link"/>
    <child link = "mirror_base_link"/>
    <origin xyz = "0 ${component_plate_x + c_middle_y} 0"/>
  </joint>

  <xacro:include filename="left_xacro.xacro"/>

  <joint name="left_xacro_joint" type="fixed">
    <parent link="mirror_base_link"/>
    <child link="circular_plate_link"/> <!-- Assuming there's a link in left_xacro.xacro named base_link_left_xacro -->
    <origin xyz="0 ${c_middle_y/2} ${c_middle_z/2}"/> <!-- Adjust the origin as needed -->
  </joint>

  <xacro:include filename="right_xacro.xacro"/>

  <joint name="right_xacro_joint" type="fixed">
    <parent link="base_link"/>
    <child link="r_circular_plate_link"/>
    <origin xyz="0 ${-c_middle_y/2} ${c_middle_z/2}"/>
  </joint>

</robot>

