<?xml version="1.0"?>
<!-- Content in right_xacro.xacro -->
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minesweeper_right">
  <link name="right_base_link"/>

  <xacro:property name="r_circular_plate_length" value="0.0005"/>
  <xacro:property name="r_circular_plate_radius" value="0.03"/>

  <xacro:property name="r_extruded_rod_radius" value="0.015"/>
  <xacro:property name="r_extruded_rod_length" value="0.1"/>


  <link name = "r_circular_plate_link">
    <visual>
        <geometry>
            <cylinder length="${r_circular_plate_length}" radius="${r_circular_plate_radius}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy="${pi/2} 0 0"/>
    </visual>
    <visual>
        <geometry>
            <cylinder length="${r_extruded_rod_length}" radius="${r_extruded_rod_radius}"/>
        </geometry>
        <origin xyz = "0 ${-r_circular_plate_length - r_extruded_rod_length/2} 0" rpy = "${pi/2} 0 0"/>
    </visual>
  </link>

  <joint name="r_circular_plate_joint" type="fixed">
    <parent link="right_base_link"/>
    <child link="r_circular_plate_link"/>
  </joint>

  <xacro:property name="r_bracket_length" value="0.04"/>
  <xacro:property name="r_bracket_radius" value="0.02"/>
  <xacro:property name="r_bracket_offset" value="0.03"/>

  <link name="r_bracket_link">
    <visual>
        <geometry>
            <cylinder length = "${r_bracket_length}" radius="${r_bracket_radius}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="r_bracket_joint" type="fixed">
    <parent link ="r_circular_plate_link"/>
    <child link ="r_bracket_link"/>
    <origin xyz="0 ${-r_circular_plate_length/2 - r_bracket_offset - r_bracket_length/2} 0" rpy="${pi/2} 0 0"/>
  </joint>

  <xacro:property name="r_rot_bracket_length" value="0.04"/>
  <xacro:property name="r_rot_bracket_radius" value="0.02"/>
  <xacro:property name="r_leg_x" value="0.056"/>
  <xacro:property name="r_leg_y" value="0.0279"/>
  <xacro:property name="r_leg_z" value="0.0254"/>


  <link name = "r_rot_bracket_link">
    <visual>
        <geometry>
            <cylinder length = "${r_rot_bracket_length}" radius="${r_rot_bracket_radius}"/>
        </geometry>
        <origin xyz = "0 0 0" rpy="0 0 0"/>
    </visual>
    <visual>
      <geometry>
        <box size = "${r_leg_x} ${r_leg_y} ${r_leg_z}"/>
      </geometry>
      <origin xyz = "${r_leg_x/2} ${-r_leg_y/2} 0" rpy="0 0 ${-pi/6}"/>
    </visual>
    <visual>
      <geometry>
        <box size = "${r_leg_x} ${r_leg_y} ${r_leg_z}"/>
      </geometry>
      <origin xyz = "${-r_leg_x/2} ${-r_leg_y/2} 0" rpy="0 0 ${pi/6}"/>
    </visual>
  </link>

  <joint name="r_rot_bracket_joint" type="revolute">
    <parent link ="r_bracket_link"/>
    <child link ="r_rot_bracket_link"/>
    <origin xyz= "0 0 ${r_rot_bracket_length/2 + r_bracket_length/2}" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
  </joint>

  <xacro:property name="r_metal_leg_x" value="0.164"/>
  <xacro:property name="r_metal_leg_y" value="0.0218"/>
  <xacro:property name="r_metal_leg_z" value="0.0218"/>

  <link name="r_metal_leg_link">
    <visual>
      <geometry>
        <box size = "${r_metal_leg_x} ${r_metal_leg_y} ${r_metal_leg_z}"/>
      </geometry>
      <origin xyz = "0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name = "r_metal_leg_joint" type="fixed">
    <parent link = "r_rot_bracket_link"/>
    <child link = "r_metal_leg_link"/>
    <origin xyz = "${(r_metal_leg_x/2 + r_leg_x/2 + r_rot_bracket_radius + 0.01) *0.866 } ${-1*(r_metal_leg_x/2 + r_leg_x/2+ r_rot_bracket_radius+ 0.01) *0.5} 0" rpy = "0 0 ${-pi/6}"/>
  </joint>

  <xacro:property name="r_metal_leg_mirror_x" value="0.08"/>

  <link name="r_metal_leg_mirror_link">
    <visual>
      <geometry>
        <box size = "${r_metal_leg_mirror_x} ${r_metal_leg_y} ${r_metal_leg_z}"/>
      </geometry>
      <origin xyz = "0 0 0" rpy="0 0 0"/>
    </visual>
  </link>
  <joint name = "r_metal_leg_mirror_joint" type="fixed">
    <parent link = "r_rot_bracket_link"/>
    <child link = "r_metal_leg_mirror_link"/>
    <origin xyz = "${-1*(r_metal_leg_mirror_x/2 + r_leg_x/2 + r_rot_bracket_radius + 0.01) *0.866 } ${-1*(r_metal_leg_mirror_x/2 + r_leg_x/2+ r_rot_bracket_radius+ 0.01) *0.5} 0" rpy = "0 0 ${pi/6}"/>
  </joint>

  <xacro:property name="r_bjw_o_radius" value="0.0109"/>
  <xacro:property name="r_bjw_o_length" value="0.03"/>


  <link name="r_bjw_link">
    <visual>
      <geometry>
        <cylinder radius="${r_bjw_o_radius}" length="${r_bjw_o_length}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="r_bjw_joint" type="revolute">
    <parent link="r_metal_leg_mirror_link"/>
    <child link="r_bjw_link"/>
    <origin xyz ="${-1*(r_metal_leg_mirror_x/2-r_bjw_o_radius)} 0 ${1*(r_metal_leg_z/2 + r_bjw_o_length/2)}" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
  </joint>

  <link name = "r_short_leg_link">
    <visual>
      <geometry>
        <box size="${r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius} ${r_metal_leg_y} ${r_metal_leg_z}" rpy="0 0 0"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="r_short_leg_joint" type="fixed">
    <parent link="r_bjw_link"/>
    <child link="r_short_leg_link"/>
    <origin xyz="${-1*(r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius)/2} 0 0" rpy="0 0 0"/>
  </joint>

    <link name = "r_short_leg_two_link">
    <visual>
      <geometry>
        <box size="${r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius} ${r_metal_leg_y} ${r_metal_leg_z}" rpy="0 0 0"/>
      </geometry>
      <origin xyz="${(r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius)/2} 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="r_short_leg_two_joint" type="fixed">
    <parent link="r_bjw_link"/>
    <child link="r_short_leg_two_link"/>
    <origin xyz="0 0 0" rpy="0 0 ${-pi/3}"/>
  </joint>

  <xacro:property name="r_wheel_length" value="0.03"/>
  <xacro:property name="r_wheel_radius" value="0.03"/>

  <link name="r_wheel_one">
    <visual>
      <geometry>
        <cylinder length="${r_wheel_length}" radius="${r_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="r_wheel_one_joint" type="revolute">
    <parent link="r_metal_leg_link"/>
    <child link="r_wheel_one"/>
    <origin xyz="${r_metal_leg_x/2} 0 ${1*(r_metal_leg_z/2 + r_wheel_length/2)}" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
  </joint>
    
  <link name="r_wheel_two">
    <visual>
      <geometry>
        <cylinder length="${r_wheel_length}" radius="${r_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>    

  <joint name="r_wheel_two_joint" type="revolute">
    <parent link="r_short_leg_two_link"/>
    <child link="r_wheel_two"/>
    <origin xyz="${(r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius)} 0 ${1*(r_metal_leg_z/2 + r_wheel_length/2)}" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
  </joint>  

  <link name="r_wheel_three">
    <visual>
      <geometry>
        <cylinder length="${r_wheel_length}" radius="${r_wheel_radius}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
  </link>    

  <joint name="r_wheel_three_joint" type="revolute">
    <parent link="r_short_leg_link"/>
    <child link="r_wheel_three"/>
    <origin xyz="${-1*(r_metal_leg_x - r_metal_leg_mirror_x + r_bjw_o_radius)/2} 0 ${1*(r_metal_leg_z/2 + r_wheel_length/2)}" rpy="0 0 0"/>
    <limit lower="-1.57" upper="1.57" effort="10" velocity="3"/>
  </joint>  

</robot>


